/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface IeaField {
    'className': string;
    'id': string;
    'label': string;
    'pattern': string;
    'placeholder': string;
    'type': string;
    'value': string;
  }
  interface IeaFieldAttributes extends StencilHTMLAttributes {
    'className'?: string;
    'id'?: string;
    'label'?: string;
    'pattern'?: string;
    'placeholder'?: string;
    'type'?: string;
    'value'?: string;
  }

  interface IeaFooterNav {
    'name': string;
  }
  interface IeaFooterNavAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface IeaGlobalNavDove {
    'expanded': boolean;
  }
  interface IeaGlobalNavDoveAttributes extends StencilHTMLAttributes {
    'expanded'?: boolean;
  }

  interface IeaGlobalNavMagnum {
    'expanded': boolean;
  }
  interface IeaGlobalNavMagnumAttributes extends StencilHTMLAttributes {
    'expanded'?: boolean;
  }

  interface IeaHeroDove {
    'alt': string;
    'bodycopy': string;
    'heading': string;
    'headingLevel': number;
    'src': string;
    'subheading': string;
    'target': string;
    'theme': string;
  }
  interface IeaHeroDoveAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'bodycopy'?: string;
    'heading'?: string;
    'headingLevel'?: number;
    'src'?: string;
    'subheading'?: string;
    'target'?: string;
    'theme'?: string;
  }

  interface IeaHeroMagnum {
    'alt': string;
    'bodycopy': string;
    'heading': string;
    'headingLevel': number;
    'src': string;
    'subheading': string;
    'target': string;
    'theme': string;
  }
  interface IeaHeroMagnumAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'bodycopy'?: string;
    'heading'?: string;
    'headingLevel'?: number;
    'src'?: string;
    'subheading'?: string;
    'target'?: string;
    'theme'?: string;
  }

  interface AupImg {
    'alt': string;
    'class': string;
    'height': string;
    'sizes': string;
    'src': string;
    'srcset': string;
    'width': string;
  }
  interface AupImgAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'class'?: string;
    'height'?: string;
    'onLoad'?: (event: CustomEvent) => void;
    'sizes'?: string;
    'src'?: string;
    'srcset'?: string;
    'width'?: string;
  }

  interface IeaLazy {
    'placeholder': string;
  }
  interface IeaLazyAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
  }

  interface IeaLogo {
    'alt': string;
    'href': string;
    'src': string;
  }
  interface IeaLogoAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'href'?: string;
    'src'?: string;
  }

  interface IeaLogoMagnum {
    'alt': string;
    'href': string;
    'src': string;
  }
  interface IeaLogoMagnumAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'href'?: string;
    'src'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }

  interface IeaScrollPosition {
    'watch': string;
  }
  interface IeaScrollPositionAttributes extends StencilHTMLAttributes {
    'onScrollY'?: (event: CustomEvent) => void;
    'watch'?: string;
  }

  interface IeaSkipToContent {
    'contentId': string;
    'text': string;
  }
  interface IeaSkipToContentAttributes extends StencilHTMLAttributes {
    'contentId'?: string;
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IeaField': Components.IeaField;
    'IeaFooterNav': Components.IeaFooterNav;
    'IeaGlobalNavDove': Components.IeaGlobalNavDove;
    'IeaGlobalNavMagnum': Components.IeaGlobalNavMagnum;
    'IeaHeroDove': Components.IeaHeroDove;
    'IeaHeroMagnum': Components.IeaHeroMagnum;
    'AupImg': Components.AupImg;
    'IeaLazy': Components.IeaLazy;
    'IeaLogo': Components.IeaLogo;
    'IeaLogoMagnum': Components.IeaLogoMagnum;
    'MyComponent': Components.MyComponent;
    'IeaScrollPosition': Components.IeaScrollPosition;
    'IeaSkipToContent': Components.IeaSkipToContent;
  }

  interface StencilIntrinsicElements {
    'iea-field': Components.IeaFieldAttributes;
    'iea-footer-nav': Components.IeaFooterNavAttributes;
    'iea-global-nav-dove': Components.IeaGlobalNavDoveAttributes;
    'iea-global-nav-magnum': Components.IeaGlobalNavMagnumAttributes;
    'iea-hero-dove': Components.IeaHeroDoveAttributes;
    'iea-hero-magnum': Components.IeaHeroMagnumAttributes;
    'aup-img': Components.AupImgAttributes;
    'iea-lazy': Components.IeaLazyAttributes;
    'iea-logo': Components.IeaLogoAttributes;
    'iea-logo-magnum': Components.IeaLogoMagnumAttributes;
    'my-component': Components.MyComponentAttributes;
    'iea-scroll-position': Components.IeaScrollPositionAttributes;
    'iea-skip-to-content': Components.IeaSkipToContentAttributes;
  }


  interface HTMLIeaFieldElement extends Components.IeaField, HTMLStencilElement {}
  var HTMLIeaFieldElement: {
    prototype: HTMLIeaFieldElement;
    new (): HTMLIeaFieldElement;
  };

  interface HTMLIeaFooterNavElement extends Components.IeaFooterNav, HTMLStencilElement {}
  var HTMLIeaFooterNavElement: {
    prototype: HTMLIeaFooterNavElement;
    new (): HTMLIeaFooterNavElement;
  };

  interface HTMLIeaGlobalNavDoveElement extends Components.IeaGlobalNavDove, HTMLStencilElement {}
  var HTMLIeaGlobalNavDoveElement: {
    prototype: HTMLIeaGlobalNavDoveElement;
    new (): HTMLIeaGlobalNavDoveElement;
  };

  interface HTMLIeaGlobalNavMagnumElement extends Components.IeaGlobalNavMagnum, HTMLStencilElement {}
  var HTMLIeaGlobalNavMagnumElement: {
    prototype: HTMLIeaGlobalNavMagnumElement;
    new (): HTMLIeaGlobalNavMagnumElement;
  };

  interface HTMLIeaHeroDoveElement extends Components.IeaHeroDove, HTMLStencilElement {}
  var HTMLIeaHeroDoveElement: {
    prototype: HTMLIeaHeroDoveElement;
    new (): HTMLIeaHeroDoveElement;
  };

  interface HTMLIeaHeroMagnumElement extends Components.IeaHeroMagnum, HTMLStencilElement {}
  var HTMLIeaHeroMagnumElement: {
    prototype: HTMLIeaHeroMagnumElement;
    new (): HTMLIeaHeroMagnumElement;
  };

  interface HTMLAupImgElement extends Components.AupImg, HTMLStencilElement {}
  var HTMLAupImgElement: {
    prototype: HTMLAupImgElement;
    new (): HTMLAupImgElement;
  };

  interface HTMLIeaLazyElement extends Components.IeaLazy, HTMLStencilElement {}
  var HTMLIeaLazyElement: {
    prototype: HTMLIeaLazyElement;
    new (): HTMLIeaLazyElement;
  };

  interface HTMLIeaLogoElement extends Components.IeaLogo, HTMLStencilElement {}
  var HTMLIeaLogoElement: {
    prototype: HTMLIeaLogoElement;
    new (): HTMLIeaLogoElement;
  };

  interface HTMLIeaLogoMagnumElement extends Components.IeaLogoMagnum, HTMLStencilElement {}
  var HTMLIeaLogoMagnumElement: {
    prototype: HTMLIeaLogoMagnumElement;
    new (): HTMLIeaLogoMagnumElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLIeaScrollPositionElement extends Components.IeaScrollPosition, HTMLStencilElement {}
  var HTMLIeaScrollPositionElement: {
    prototype: HTMLIeaScrollPositionElement;
    new (): HTMLIeaScrollPositionElement;
  };

  interface HTMLIeaSkipToContentElement extends Components.IeaSkipToContent, HTMLStencilElement {}
  var HTMLIeaSkipToContentElement: {
    prototype: HTMLIeaSkipToContentElement;
    new (): HTMLIeaSkipToContentElement;
  };

  interface HTMLElementTagNameMap {
    'iea-field': HTMLIeaFieldElement
    'iea-footer-nav': HTMLIeaFooterNavElement
    'iea-global-nav-dove': HTMLIeaGlobalNavDoveElement
    'iea-global-nav-magnum': HTMLIeaGlobalNavMagnumElement
    'iea-hero-dove': HTMLIeaHeroDoveElement
    'iea-hero-magnum': HTMLIeaHeroMagnumElement
    'aup-img': HTMLAupImgElement
    'iea-lazy': HTMLIeaLazyElement
    'iea-logo': HTMLIeaLogoElement
    'iea-logo-magnum': HTMLIeaLogoMagnumElement
    'my-component': HTMLMyComponentElement
    'iea-scroll-position': HTMLIeaScrollPositionElement
    'iea-skip-to-content': HTMLIeaSkipToContentElement
  }

  interface ElementTagNameMap {
    'iea-field': HTMLIeaFieldElement;
    'iea-footer-nav': HTMLIeaFooterNavElement;
    'iea-global-nav-dove': HTMLIeaGlobalNavDoveElement;
    'iea-global-nav-magnum': HTMLIeaGlobalNavMagnumElement;
    'iea-hero-dove': HTMLIeaHeroDoveElement;
    'iea-hero-magnum': HTMLIeaHeroMagnumElement;
    'aup-img': HTMLAupImgElement;
    'iea-lazy': HTMLIeaLazyElement;
    'iea-logo': HTMLIeaLogoElement;
    'iea-logo-magnum': HTMLIeaLogoMagnumElement;
    'my-component': HTMLMyComponentElement;
    'iea-scroll-position': HTMLIeaScrollPositionElement;
    'iea-skip-to-content': HTMLIeaSkipToContentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
