/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface IeaFooterNav {
    'name': string;
  }
  interface IeaFooterNavAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface IeaGlobalNav {
    'logoIndex': number;
  }
  interface IeaGlobalNavAttributes extends StencilHTMLAttributes {
    'logoIndex'?: number;
  }

  interface IeaHero {
    'alt': string;
    'bodycopy': string;
    'heading': string;
    'headingLevel': number;
    'src': string;
  }
  interface IeaHeroAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'bodycopy'?: string;
    'heading'?: string;
    'headingLevel'?: number;
    'src'?: string;
  }

  interface IeaLazy {
    'placeholder': string;
  }
  interface IeaLazyAttributes extends StencilHTMLAttributes {
    'placeholder'?: string;
  }

  interface IeaLogo {
    'alt': string;
    'href': string;
    'src': string;
  }
  interface IeaLogoAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'href'?: string;
    'src'?: string;
  }

  interface MyComponent {
    'first': string;
    'last': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'first'?: string;
    'last'?: string;
  }

  interface IeaSkipToContent {
    'contentId': string;
    'text': string;
  }
  interface IeaSkipToContentAttributes extends StencilHTMLAttributes {
    'contentId'?: string;
    'text'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'IeaFooterNav': Components.IeaFooterNav;
    'IeaGlobalNav': Components.IeaGlobalNav;
    'IeaHero': Components.IeaHero;
    'IeaLazy': Components.IeaLazy;
    'IeaLogo': Components.IeaLogo;
    'MyComponent': Components.MyComponent;
    'IeaSkipToContent': Components.IeaSkipToContent;
  }

  interface StencilIntrinsicElements {
    'iea-footer-nav': Components.IeaFooterNavAttributes;
    'iea-global-nav': Components.IeaGlobalNavAttributes;
    'iea-hero': Components.IeaHeroAttributes;
    'iea-lazy': Components.IeaLazyAttributes;
    'iea-logo': Components.IeaLogoAttributes;
    'my-component': Components.MyComponentAttributes;
    'iea-skip-to-content': Components.IeaSkipToContentAttributes;
  }


  interface HTMLIeaFooterNavElement extends Components.IeaFooterNav, HTMLStencilElement {}
  var HTMLIeaFooterNavElement: {
    prototype: HTMLIeaFooterNavElement;
    new (): HTMLIeaFooterNavElement;
  };

  interface HTMLIeaGlobalNavElement extends Components.IeaGlobalNav, HTMLStencilElement {}
  var HTMLIeaGlobalNavElement: {
    prototype: HTMLIeaGlobalNavElement;
    new (): HTMLIeaGlobalNavElement;
  };

  interface HTMLIeaHeroElement extends Components.IeaHero, HTMLStencilElement {}
  var HTMLIeaHeroElement: {
    prototype: HTMLIeaHeroElement;
    new (): HTMLIeaHeroElement;
  };

  interface HTMLIeaLazyElement extends Components.IeaLazy, HTMLStencilElement {}
  var HTMLIeaLazyElement: {
    prototype: HTMLIeaLazyElement;
    new (): HTMLIeaLazyElement;
  };

  interface HTMLIeaLogoElement extends Components.IeaLogo, HTMLStencilElement {}
  var HTMLIeaLogoElement: {
    prototype: HTMLIeaLogoElement;
    new (): HTMLIeaLogoElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLIeaSkipToContentElement extends Components.IeaSkipToContent, HTMLStencilElement {}
  var HTMLIeaSkipToContentElement: {
    prototype: HTMLIeaSkipToContentElement;
    new (): HTMLIeaSkipToContentElement;
  };

  interface HTMLElementTagNameMap {
    'iea-footer-nav': HTMLIeaFooterNavElement
    'iea-global-nav': HTMLIeaGlobalNavElement
    'iea-hero': HTMLIeaHeroElement
    'iea-lazy': HTMLIeaLazyElement
    'iea-logo': HTMLIeaLogoElement
    'my-component': HTMLMyComponentElement
    'iea-skip-to-content': HTMLIeaSkipToContentElement
  }

  interface ElementTagNameMap {
    'iea-footer-nav': HTMLIeaFooterNavElement;
    'iea-global-nav': HTMLIeaGlobalNavElement;
    'iea-hero': HTMLIeaHeroElement;
    'iea-lazy': HTMLIeaLazyElement;
    'iea-logo': HTMLIeaLogoElement;
    'my-component': HTMLMyComponentElement;
    'iea-skip-to-content': HTMLIeaSkipToContentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
